workflows:
  eleague_android:
    name: eLeague Hub Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.eleaguehub.app"

    scripts:
      - name: Get Flutter Packages
        script: |
          cd frontend
          flutter pub get

      - name: Build Release APK
        script: |
          cd frontend
          flutter build apk --release

    artifacts:
      - frontend/build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - mohammedauwalnasara@gmail.com